CREATE TABLE CONTENTS(
	ID int(6) unsigned NOT NULL AUTO_INCREMENT,
	NICK varchar(24) NOT NULL,
	CONTENTS TEXT NOT NULL,
    REG_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(ID)
);


CREATE TABLE ADMIN_PW(
	ID int(6) unsigned NOT NULL AUTO_INCREMENT,
    PW VARCHAR(40) NOT NULL,
    PRIMARY KEY(ID)
);

INSERT INTO ADMIN_PW (PW) VALUES('dmdbounce!130');